-- V47: capa analítica para IA energética
create table if not exists public.meter_monthly_metrics (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  meter_id uuid not null references public.meters(id) on delete cascade,
  period text not null,
  consumption_kwh numeric not null default 0,
  reactive_kvarh numeric not null default 0,
  max_demand_kw numeric not null default 0,
  contracted_kw numeric not null default 0,
  utilization_percent numeric not null default 0,
  power_factor numeric,
  reactive_surcharge_percent numeric not null default 0,
  total_amount numeric not null default 0,
  tariff_code text,
  invoice_count integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (organization_id, meter_id, period)
);

create table if not exists public.meter_energy_snapshot (
  meter_id uuid primary key references public.meters(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  latest_period text,
  latest_kwh numeric not null default 0,
  avg_kwh_6m numeric not null default 0,
  avg_kwh_12m numeric not null default 0,
  latest_amount numeric not null default 0,
  avg_amount_6m numeric not null default 0,
  latest_demand_kw numeric not null default 0,
  max_demand_12m numeric not null default 0,
  contracted_kw numeric not null default 0,
  excess_kw numeric not null default 0,
  utilization_percent numeric not null default 0,
  power_factor numeric,
  min_power_factor_6m numeric,
  reactive_surcharge_percent numeric not null default 0,
  current_tariff_code text,
  months_without_invoice integer not null default 0,
  status text,
  consumption_change_percent numeric,
  amount_change_percent numeric,
  anomaly_score numeric not null default 0,
  monthly_saving_power numeric not null default 0,
  monthly_saving_reactive numeric not null default 0,
  monthly_saving_tariff numeric not null default 0,
  total_monthly_saving numeric not null default 0,
  total_annual_saving numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.energy_findings (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  meter_id uuid references public.meters(id) on delete cascade,
  finding_type text not null,
  severity text not null default 'medium',
  title text not null,
  diagnosis text not null,
  evidence jsonb not null default '{}'::jsonb,
  recommended_action text not null,
  validation_required text,
  investment_type text not null default 'unknown',
  estimated_monthly_saving numeric not null default 0,
  estimated_annual_saving numeric not null default 0,
  confidence numeric not null default 0,
  status text not null default 'open',
  detected_period text,
  fingerprint text not null,
  detected_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  unique (organization_id, fingerprint)
);
